The `refa` module offers necessary classes to build a complete techno-economic analysis of different capacity upgrade options.

In [14]:
from refa import (
    LineDesign, Conductor, Line, Rebuild, Reconductoring, VoltageUpgrade, HVDC, Existing, Analysis
)

Default constuctors are included in `refa.defaults` to illustrate how different inputs can be entered.

In [15]:
from refa.defaults import (
    default_economics,
    default_clear_environment,
    default_conductor,
    default_structure_config_ac,
    default_structure_config_dc
)

my_conductor = default_conductor()
my_environment = default_clear_environment()
my_structure_config_ac = default_structure_config_ac()
my_structure_config_dc = default_structure_config_dc()
my_economics = default_economics()

Standard NESC 250B rule loading profiles are provided at `refa.standards`.

In [16]:
from refa.standards import nesc_250b_heavy

my_loading = nesc_250b_heavy()
print(my_loading)

wind_ice_temperature_c=-5.0 pressure_pa=700.0 ice_thickness_m=0.025 ice_density_kg_per_m3=915.0 additive_loading_n_per_m=4.4

To create a `Line`, you should build a `LineDesign` and a `Conductor`. Typical conductor sizes can be found in `refa.defaults`.

In [17]:
from refa.defaults import acsr_795_0_drake, acss_795_0_cuckoo, accc_1035_dublin, load_conductors_from_csv

line_design1 = LineDesign(
    environment=my_environment,
    nbr_circuits=1,
    nbr_bundles=3,
    nbr_conds_per_bundle=1,
    length_km=10,
    avg_span_m=250,
    max_span_m=300
)
line_design2 = LineDesign(
    environment=my_environment,
    nbr_circuits=1,
    nbr_bundles=3,
    nbr_conds_per_bundle=1,
    length_km=30,
    avg_span_m=300,
    max_span_m=300
)
print("Line design -> ", line_design1)

conductor = Conductor(
        type='ACSR',
        code='266.8_PARTRIDGE',
        area_mm2=157.0,
        diameter_mm=16.0,
        weight_n_per_m=5.36,
        conductor_rts_kn=50.26,
        dol_per_1000_ft=735.0,
        inst_dol_per_1000_ft=1027.0,
        accessories_dol_per_1000_ft=263.0,
        str_costs_dol=0.0,
        temp_dc_c=20.0,
        temp_low_c=25.0,
        temp_high_c=75.0,
        max_temperature_c=100.0,
        res_dc_ohm_per_m=0.000209,
        res_low_ohm_per_m=0.000209,
        res_high_ohm_per_m=0.000256,
        elastic_modulus_gpa=75.5,
        coeff_thermal_expan_per_cel=1.92e-05,
        emissivity=0.5,
        solar_absorptivity=0.5
)
print("Conductor using constructor -> ", conductor)

conductor1 = acss_795_0_cuckoo()
conductor2 = acsr_795_0_drake()
conductor3 = accc_1035_dublin()
print("Conductor from default database -> ", conductor1)

conductors = load_conductors_from_csv('input_data_raw/conductors.csv')
print("Conductor from csv file -> ", conductors.acsr_477_0_pelican())

Line design ->  environment=Environment(date=datetime.date(2026, 4, 27), latitude=45.0, elevation_m=100.0, wind_speed_m_per_s=1.0, wind_angle=0, cw_angle_direction_rel_to_north=0, hour=12, atmosphere={'A': -42.2391, 'B': 63.8044, 'C': -1.922, 'D': 0.0346921, 'E': -0.000361118, 'F': 1.94318e-06, 'G': -4.07608e-09}, ambient_temperature_c=25.0, weather_correction_factor=1.0, rugosity_coefficient=0.82) nbr_circuits=1 nbr_bundles=3 nbr_conds_per_bundle=1 length_km=10.0 avg_span_m=250.0 max_span_m=300.0 nbr_structures=41 max_sag_m=None
Conductor using constructor ->  type='ACSR' code='266.8_PARTRIDGE' area_mm2=157.0 diameter_mm=16.0 weight_n_per_m=5.36 conductor_rts_kn=50.26 dol_per_1000_ft=735.0 inst_dol_per_1000_ft=1027.0 accessories_dol_per_1000_ft=263.0 str_costs_dol=0.0 temp_dc_c=20.0 temp_low_c=25.0 temp_high_c=75.0 max_temperature_c=100.0 res_dc_ohm_per_m=0.000209 res_low_ohm_per_m=0.000209 res_high_ohm_per_m=0.000256 elastic_modulus_gpa=75.5 coeff_thermal_expan_per_cel=1.92e-05 emissivity=0.5 solar_absorptivity=0.5
Conductor from default database ->  type='ACSS' code='795.0_CUCKOO' area_mm2=455.0 diameter_mm=28.0 weight_n_per_m=14.93 conductor_rts_kn=96.53 dol_per_1000_ft=1830.0 inst_dol_per_1000_ft=2291.0 accessories_dol_per_1000_ft=263.0 str_costs_dol=0.0 temp_dc_c=20.0 temp_low_c=25.0 temp_high_c=75.0 max_temperature_c=200.0 res_dc_ohm_per_m=6.97e-05 res_low_ohm_per_m=7.09e-05 res_high_ohm_per_m=8.63e-05 elastic_modulus_gpa=65.25 coeff_thermal_expan_per_cel=1.8e-05 emissivity=0.5 solar_absorptivity=0.5
Conductor from csv file ->  type='ACSR' code='477.0_PELICAN' area_mm2=256.0 diameter_mm=21.0 weight_n_per_m=7.55 conductor_rts_kn=52.49 dol_per_1000_ft=940.0 inst_dol_per_1000_ft=1353.0 accessories_dol_per_1000_ft=263.0 str_costs_dol=0.0 temp_dc_c=20.0 temp_low_c=25.0 temp_high_c=75.0 max_temperature_c=100.0 res_dc_ohm_per_m=0.000118 res_low_ohm_per_m=0.000118 res_high_ohm_per_m=0.000145 elastic_modulus_gpa=66.0 coeff_thermal_expan_per_cel=2.12e-05 emissivity=0.5 solar_absorptivity=0.5

Then, a line can be created either using `Line` constructor, or directly summing a `LineDesign` and a `Conductor`.

In [18]:
line1 = Line(line_design=line_design1, conductor=conductor1)
line2 = line_design2 + conductor2
line3 = conductor3 + line_design1

print(line1)

line_design=LineDesign(environment=Environment(date=datetime.date(2026, 4, 27), latitude=45.0, elevation_m=100.0, wind_speed_m_per_s=1.0, wind_angle=0, cw_angle_direction_rel_to_north=0, hour=12, atmosphere={'A': -42.2391, 'B': 63.8044, 'C': -1.922, 'D': 0.0346921, 'E': -0.000361118, 'F': 1.94318e-06, 'G': -4.07608e-09}, ambient_temperature_c=25.0, weather_correction_factor=1.0, rugosity_coefficient=0.82), nbr_circuits=1, nbr_bundles=3, nbr_conds_per_bundle=1, length_km=10.0, avg_span_m=250.0, max_span_m=300.0, nbr_structures=41, max_sag_m=None) conductor=Conductor(type='ACSS', code='795.0_CUCKOO', area_mm2=455.0, diameter_mm=28.0, weight_n_per_m=14.93, conductor_rts_kn=96.53, dol_per_1000_ft=1830.0, inst_dol_per_1000_ft=2291.0, accessories_dol_per_1000_ft=263.0, str_costs_dol=0.0, temp_dc_c=20.0, temp_low_c=25.0, temp_high_c=75.0, max_temperature_c=200.0, res_dc_ohm_per_m=6.97e-05, res_low_ohm_per_m=7.09e-05, res_high_ohm_per_m=8.63e-05, elastic_modulus_gpa=65.25, coeff_thermal_expan_per_cel=1.8e-05, emissivity=0.5, solar_absorptivity=0.5)

Different technical calculations can be conducted using a `Line` object.

In [19]:
temperature_from_current, resistance_from_current = line1.calculate_temperature_and_resistance_at_current(current_a=1400)
temperature_from_p_and_v, resistance_from_p_and_v = line1.calculate_temperature_and_resistance_at_current(power_mw=550, voltage_kv=345)
print(f"Conductor temperature when current is provided -> {temperature_from_current} deg. Cel")
print(f"Conductor resistance when current is provided -> {resistance_from_current} Ohm/m")
print(f"Conductor temperature when power and voltage are provided -> {temperature_from_p_and_v} deg. Cel")
print(f"Conductor resistance when power and voltage are provided -> {resistance_from_p_and_v} Ohm/m")

ampacity = line1.calculate_ampacity()
print(f"Ampacity -> {ampacity} Amps")

sag_from_peak_current = line1.calculate_sag(current_a=1400, initial_tension_percentage=0.2)
sag_from_power_and_voltage = line1.calculate_sag(power_mw=500, voltage_kv=230, initial_tension_percentage=0.2)
sag_from_conductor_temperature = line1.calculate_sag(temp_at_current_c=85, initial_tension_percentage=0.2)
sag_from_loading_profile = line1.calculate_sag(loading_conditions=my_loading, initial_tension_percentage=0.2)
print(f"Sag when peak current is provided -> {sag_from_peak_current}")
print(f"Sag when conductor temperature is provided -> {sag_from_conductor_temperature}")
print(f"Sag when a wind/ice loading profile is provided -> {sag_from_loading_profile}")

corona_inception_voltage, corona_voltage_gradient = line1.calculate_corona_discharge(
    structure_config=my_structure_config_ac
)
print(f"Corona Inception voltage -> {corona_inception_voltage} kV")
print(f"Corona voltage gradient -> {corona_voltage_gradient} kV/cm")

Conductor temperature when current is provided -> 200.0011444091797 deg. Cel
Conductor resistance when current is provided -> 0.00012480035247802734 Ohm/m
Conductor temperature when power and voltage are provided -> 105.96084594726562 deg. Cel
Conductor resistance when power and voltage are provided -> 9.583594055175781e-05 Ohm/m
Ampacity -> 1398.4137313039237 Amps
Sag when peak current is provided -> 13.559024576990398
Sag when conductor temperature is provided -> 10.825531018379806
Sag when a wind/ice loading profile is provided -> 11.551659735073567
Corona Inception voltage -> 230.18425980317025 kV
Corona voltage gradient -> 29.074721839309312 kV/cm

Also, losses and congestion of a given `Line` can be calculated using available functions.

In [29]:
resistive_line_losses_from_current = line1.calculate_resistive_line_losses(current_a=1400, voltage_kv=230, load_factor=0.55)
resistive_line_losses_from_power = line1.calculate_resistive_line_losses(power_mw=550, voltage_kv=230, load_factor=0.6)
print(f"Resistive line losses when current is provided -> {resistive_line_losses_from_current} MWh/m")
print(f"Resistive line losses when power is provided -> {resistive_line_losses_from_power} MWh/m")

corona_discharge_losses = line1.calculate_corona_discharge_losses(
    voltage_kv=345, load_factor=0.6, structure_config=my_structure_config_ac
    )
print(f"Corona discharge losses -> {corona_discharge_losses} MWh/m")

corona_discharge_losses_dc = line1.calculate_corona_discharge_losses(
    voltage_kv=345, load_factor=0.6, structure_config=my_structure_config_dc, is_hvdc=True
    )
print(f"Corona discharge losses (DC line) -> {corona_discharge_losses_dc} MWh/m")

congestion_from_current = line1.calculate_congestion(current_a=1500, voltage_kv=230)
congestion_from_power = line1.calculate_congestion(power_mw=700, voltage_kv=230)
print(f"Congestion when current is provided -> {congestion_from_current} MW")
print(f"Congestion when power is provided -> {congestion_from_power} MW")

Resistive line losses when current is provided -> 2.0900977413003057 MWh/m
Resistive line losses when power is provided -> 2.6719863714980816 MWh/m
Corona discharge losses -> 0.6223302061304375 MWh/m
Corona discharge losses (DC line) -> 0.027281108138393347 MWh/m
Congestion when current is provided -> 1.3703680554715199 MW
Congestion when power is provided -> 14.588368047907396 MW

The overall technical performance of a `Line` can be calculated in a single function call. The basic usage calculates only ampacity and sag when current or (power+voltage) are provided; then includes losses if load_factor is provided, and corona discharge if structure_config is provided.

In [21]:
technical_perf_from_current = line1.calculate_overall_technical_performance(current_a=1500)
print(f"Overall performance when only current is provided -> {technical_perf_from_current}")

technical_perf_from_power_and_voltage = line1.calculate_overall_technical_performance(
    power_mw=500, voltage_kv=230
)
print(f"Overall performance when power and voltage are provided -> {technical_perf_from_power_and_voltage}")

technical_perf_including_losses = line1.calculate_overall_technical_performance(
    current_a=1500, load_factor=0.6
)
print(f"Overall performance including losses -> {technical_perf_from_power_and_voltage}")

technical_perf_including_corona = line1.calculate_overall_technical_performance(
    current_a=1500, voltage_kv=230, load_factor=0.6, structure_config=my_structure_config_ac
)
print(f"Overall performance including corona discharg -> {technical_perf_including_corona}")

voltage_kv required to calculate losses and congestion.
Overall performance when only current is provided -> {'ampacity_a': np.float64(1398.4137313039237), 'sag_m': np.float64(14.09531244404144)}
Overall performance when power and voltage are provided -> {'ampacity_a': np.float64(1398.4137313039237), 'sag_m': np.float64(12.820450736624649), 'congestion_mw': 0}
voltage_kv required to calculate losses and congestion.
Overall performance including losses -> {'ampacity_a': np.float64(1398.4137313039237), 'sag_m': np.float64(12.820450736624649), 'congestion_mw': 0}
Overall performance including corona discharg -> {'ampacity_a': np.float64(1398.4137313039237), 'sag_m': np.float64(14.09531244404144), 'congestion_mw': np.float64(1.3703680554715199), 'resistive_losses_mwh_per_m': np.float64(2.462707896036645), 'corona_inception_voltage_kv': np.float64(230.18425980317025), 'corona_voltage_gradient_kv_per_cm': np.float64(29.074721839309312), 'corona_losses_mwh_per_m': 0}

An object `Line` allows to check for feasibility in terms of ampacity, sag, and corona discharge effect. The basic usage checks only for feasibility in terms of ampacity when current or (power+voltage) are provided, then includes sag when max_sag is provided, and corona discharge if structure_config is provided.

In [22]:
# line1.is_feasible(current_a=1500)
# line1.is_feasible(power_mw=700, voltage_kv=345)
# line1.is_feasible(current_a=1300, max_sag_m=10, initial_tension_percentage=0.3)
line1.is_feasible(current_a=1300, max_sag_m=15, initial_tension_percentage=0.3, 
                  structure_config=my_structure_config_ac, voltage_kv=345)

(False,
 'Corona inception voltage 230.18425980317025 kV is below the line voltage. ')

Different types of projects can be created using `a LineDesign + a list of Conductor objects` or `a list of Line Objects`.

In [23]:
rebuild_prj = Rebuild(
    conductor_list=[acsr_795_0_drake(), acss_795_0_cuckoo(), accc_1035_dublin()], 
    line_design=line_design2,
    economics=my_economics,
    power_mw=400,
    voltage_kv=230,
    structure_config=my_structure_config_ac
)
reconductoring_prj = Reconductoring(
    line_list=[line1, line2], 
    economics=my_economics,
    power_mw=400,
    voltage_kv=230,
    structure_remaining_life=25
)
voltageupgrade_prj = VoltageUpgrade(
    line_list=[line2, line1], 
    economics=my_economics,
    power_mw=400,
    voltage_kv=345, 
    structure_remaining_life=0, 
    conductor_remaining_life=0, 
)
hvdc_prj = HVDC(
    line_list=[line3, line2], 
    economics=my_economics,
    power_mw=400,
    voltage_kv=500, 
    structure_remaining_life=0, 
    conductor_remaining_life=0, 
    nbr_dc_poles_per_circuit=2
)
existing_project = Existing(
    line_list=[line1], 
    economics=my_economics,
    power_mw=400,
    voltage_kv=230,
    structure_remaining_life=25,
    conductor_remaining_life=15,
    structure_config=my_structure_config_dc
)

Each project can use internal functions to calculate different costs.

In [24]:
# rebuild_prj.calculate_total_npv(time_horizon=65)
# rebuild_prj.calculate_total_npv(time_horizon=65, load_factor=0.6)
rebuild_prj.calculate_structure_costs(time_horizon=65)
# rebuild_prj.calculate_conductor_costs(time_horizon=65)
# rebuild_prj.calculate_losses_costs(time_horizon=65, load_factor=0.6)

# reconductoring_prj.calculate_total_npv(time_horizon=65)
# reconductoring_prj.calculate_total_npv(time_horizon=65, load_factor=0.6)
# reconductoring_prj.calculate_structure_costs(time_horizon=65)
# reconductoring_prj.calculate_conductor_costs(time_horizon=65)
# reconductoring_prj.calculate_losses_costs(time_horizon=65, load_factor=0.6)
# reconductoring_prj.calculate_congestion_costs(time_horizon=65)

voltageupgrade_prj.calculate_total_npv(time_horizon=70)
hvdc_prj.calculate_total_npv(time_horizon=70, select_feasible=False)

           0    1    2    3    4    5    6    7    8    9   ...            60  \
0   4100000.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.345223e+07
1  10100000.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  3.313841e+07

    61   62   63   64   65   66   67   68   69
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[2 rows x 70 columns]

  prj_name         conductor  npv_total_project_costs_mill_dol
0     HVDC  ACCC 1035_DUBLIN                          5.199106
1     HVDC  ACSR 795.0_DRAKE                         11.650353

VoltageUpgrade and HVDC projects contain costs that are not present in other types of projects. These costs of substation, transformer, or converter modifications are currently added to the upfront capital cost, ans set as follows.

In [25]:
voltageupgrade_prj.cost_substations_transfos_dol = 1000000
hvdc_prj.cost_converters_dol = 2000000

Multiple projects can be compared using an object `Analysis` based on total net-present value of cost, or marginal costs of structures, conductors, losses, and congestion. 
By default, each line in a project is checked for feasibility in terms of ampacity, sag (if `line_obj.line_design.max_sag` is not `None`), and corona (if `project_obj.structure_config` is not `None`). This feasibility check can be deactivated by passing `select_feasible=False`.

In [26]:
refa = Analysis(project_list=[
    rebuild_prj, reconductoring_prj, voltageupgrade_prj, hvdc_prj, existing_project
    ])
# refa.compare_project_total_costs(time_horizon=70, load_factor=0.6)

# refa.compare_project_structure_costs(time_horizon=70)
# refa.compare_project_conductor_costs(time_horizon=70, select_feasible=False)
# refa.compare_project_losses_costs(time_horizon=70, load_factor=0.6)
refa.compare_project_congestion_costs(time_horizon=70)

         prj_name          conductor  npv_total_congestion_costs_mill_dol
0         Rebuild   ACSR 795.0_DRAKE                             0.573763
1         Rebuild  ACSS 795.0_CUCKOO                             0.000000
2         Rebuild   ACCC 1035_DUBLIN                             0.000000
3  Reconductoring  ACSS 795.0_CUCKOO                             0.000000
4  Reconductoring   ACSR 795.0_DRAKE                             0.573763
5  VoltageUpgrade   ACSR 795.0_DRAKE                             0.000000
6  VoltageUpgrade  ACSS 795.0_CUCKOO                             0.000000
7            HVDC   ACCC 1035_DUBLIN                             0.000000
8            HVDC   ACSR 795.0_DRAKE                             0.000000
9        Existing  ACSS 795.0_CUCKOO                             0.000000